### ISSUE TITLE
drv_usart.c是否需要和rt-thread master同步

### ISSUE THREAD

**Issue by loogg** [RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi#101]
引脚也使用cube配置

**Comment by whj4674672** [comment]
引脚目前通过 board.h 的字符串来配置，比在 cubemx 配置要显得更加方便。
现在的驱动与master分支上的drv_usart.c，有哪些不合适的地方吗？

**Comment by loogg** [comment]
> 引脚目前通过 board.h 的字符串来配置，比在 cubemx 配置要显得更加方便。
> 现在的驱动与master分支上的drv_usart.c，有哪些不合适的地方吗？

其他外设的引脚都是由cube配置的，usart使用字符串配置是有什么考究嘛，至于说方便，我反而觉得还是cube方便

**Comment by whj4674672** [comment]
@Guozhanxin 郭老师 能帮忙解释一下吗

**Comment by whj4674672** [comment]
@Guozhanxin

**Comment by Guozhanxin** [comment]
这个要作者来解释吧@thread-liu

**Comment by Guozhanxin** [comment]
是studio为了兼容其他芯片厂家的芯片，这样使用studio创建的nxp的工程，也可以直接使用uart输出了。

**Comment by loogg** [comment]
我觉得这个都是ART PI了，它就是ST，它会调用Cube生成的引脚，然后board.h里不小心配错了，会冲突可能导致问题吧

**Comment by Guozhanxin** [comment]
> 我觉得这个都是ART PI了，它就是ST，它会调用Cube生成的引脚，然后board.h里不小心配错了，会冲突可能导致问题吧

好像也是这个理

**Comment by whj4674672** [comment]
目前已经和 master 分支同步了，还增加了 UART DMA 的支持，也保留了 字符串开启串口的功能
