### ISSUE TITLE
缺少開啓支持保存 wifi 密碼到 flash 的調用，默認保存在內存。

### ISSUE THREAD

**Issue by iysheng** [RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi#121]
. 默認的 factory 工程 **easyflash 模塊**的初始化 **easyflash_init()** 未執行，導致無法保存 wlan 密碼到 flash。測試 wifi autconnect 功能 ART-Pi 斷電後就無法再次連接 wifi。順帶出現的問題是雖然保留有 easyflash 區，但是因爲沒有執行 easyflash 的初始化，所有在執行 printenv 時也會提示錯誤。
```
msh />printenv
[Flash] ENV isn't initialize OK.
```
我嘗試修改通過判斷是否開啓重連 WIFI 的宏 **RT_WLAN_AUTO_CONNECT_ENABLE** 來選擇性地執行函數 **wlan_autoconnect_init()**。目前我將這部分修改放在文件 **libraries/drivers/drv_wlan.c**，不知道是否合適 :confused:  ，所以也沒有貿然提交 pr。
```diff
diff --git a/libraries/drivers/drv_wlan.c b/libraries/drivers/drv_wlan.c
index bab6b10..d2885ef 100644
--- a/libraries/drivers/drv_wlan.c
+++ b/libraries/drivers/drv_wlan.c
@@ -227,6 +227,9 @@ int rt_hw_wlan_init(void)
     }
 
     rt_thread_t tid = RT_NULL;
+#ifdef RT_WLAN_AUTO_CONNECT_ENABLE
+    wlan_autoconnect_init();
+#endif
 
     tid = rt_thread_create("wifi_init", wifi_init_thread_entry, RT_NULL, WIFI_INIT_THREAD_STACK_SIZE, WIFI_INIT_THREAD_PRIORITY, 20);
     if (tid)

```

**Comment by whj4674672** [comment]
在设计之初考虑过，是否需要增加 easyflash 保存 wifi 账号密码的功能，最后被推翻了。
但是为了方便有这方面需求的用户，我们又提供了 art_pi_wifI 这个例程，这个就实现了 保存 wifi 账号密码的功能，同时还在目录下的 /docs 下给出了实现机制。

**Comment by whj4674672** [comment]
建议你去参考 art_pi_wifi  art_pi_net_player 这两个例程，均实现了此功能
