### ISSUE TITLE
Keil FLM下载算法的问题

### ISSUE THREAD

**Issue by jesons007** [RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi#149]
### Keil FLM 下载算法有问题，下载之后校验失败（并且还是内部flash校验失败？？？），调试发现直接进了hardfault

**Comment by whj4674672** [comment]
请提供更多的信息，建议提供 link.sct 截图，下载算法选中的界面截图，修改中断向量表截图。

**Comment by jesons007** [comment]
我写的裸机
文件没选错

ram设置足够


Load "..\\OBJ\\test.axf" 
Erase Done.
Programming Done.
Contents mismatch at: 08000020H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000021H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000022H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000023H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000024H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000025H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000026H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000027H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000028H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000029H  (Flash=FFH  Required=00H) !
Contents mismatch at: 0800002AH  (Flash=FFH  Required=00H) !
Contents mismatch at: 0800002BH  (Flash=FFH  Required=00H) !
Contents mismatch at: 0800002CH  (Flash=FFH  Required=DBH) !
Contents mismatch at: 0800002DH  (Flash=FFH  Required=02H) !
Contents mismatch at: 0800002EH  (Flash=FFH  Required=00H) !
Contents mismatch at: 0800002FH  (Flash=FFH  Required=08H) !
Contents mismatch at: 08000030H  (Flash=FFH  Required=DDH) !
Contents mismatch at: 08000031H  (Flash=FFH  Required=02H) !
Contents mismatch at: 08000032H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000033H  (Flash=FFH  Required=08H) !
Contents mismatch at: 08000034H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000035H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000036H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000037H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000038H  (Flash=FFH  Required=DFH) !
Contents mismatch at: 08000039H  (Flash=FFH  Required=02H) !
Contents mismatch at: 0800003AH  (Flash=FFH  Required=00H) !
Contents mismatch at: 0800003BH  (Flash=FFH  Required=08H) !
Contents mismatch at: 0800003CH  (Flash=FFH  Required=E1H) !
Contents mismatch at: 0800003DH  (Flash=FFH  Required=02H) !
Contents mismatch at: 0800003EH  (Flash=FFH  Required=00H) !
Contents mismatch at: 0800003FH  (Flash=FFH  Required=08H) !
Contents mismatch at: 08000040H  (Flash=FFH  Required=E3H) !
Contents mismatch at: 08000041H  (Flash=FFH  Required=02H) !
Contents mismatch at: 08000042H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000043H  (Flash=FFH  Required=08H) !
Contents mismatch at: 08000044H  (Flash=FFH  Required=E3H) !
Contents mismatch at: 08000045H  (Flash=FFH  Required=02H) !
Contents mismatch at: 08000046H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000047H  (Flash=FFH  Required=08H) !
Contents mismatch at: 08000048H  (Flash=FFH  Required=E3H) !
Contents mismatch at: 08000049H  (Flash=FFH  Required=02H) !
Contents mismatch at: 0800004AH  (Flash=FFH  Required=00H) !
Contents mismatch at: 0800004BH  (Flash=FFH  Required=08H) !
Contents mismatch at: 0800004CH  (Flash=FFH  Required=E3H) !
Contents mismatch at: 0800004DH  (Flash=FFH  Required=02H) !
Contents mismatch at: 0800004EH  (Flash=FFH  Required=00H) !
Contents mismatch at: 0800004FH  (Flash=FFH  Required=08H) !
Contents mismatch at: 08000050H  (Flash=FFH  Required=E3H) !
Contents mismatch at: 08000051H  (Flash=FFH  Required=02H) !
Contents mismatch at: 08000052H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000053H  (Flash=FFH  Required=08H) !
Contents mismatch at: 08000054H  (Flash=FFH  Required=E3H) !
Contents mismatch at: 08000055H  (Flash=FFH  Required=02H) !
Contents mismatch at: 08000056H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000057H  (Flash=FFH  Required=08H) !
Contents mismatch at: 08000058H  (Flash=FFH  Required=E3H) !
Contents mismatch at: 08000059H  (Flash=FFH  Required=02H) !
Contents mismatch at: 0800005AH  (Flash=FFH  Required=00H) !
Contents mismatch at: 0800005BH  (Flash=FFH  Required=08H) !
Contents mismatch at: 0800005CH  (Flash=FFH  Required=E3H) !
Contents mismatch at: 0800005DH  (Flash=FFH  Required=02H) !
Contents mismatch at: 0800005EH  (Flash=FFH  Required=00H) !
Contents mismatch at: 0800005FH  (Flash=FFH  Required=08H) !
Contents mismatch at: 08000060H  (Flash=FFH  Required=E3H) !
Contents mismatch at: 08000061H  (Flash=FFH  Required=02H) !
Contents mismatch at: 08000062H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000063H  (Flash=FFH  Required=08H) !
Contents mismatch at: 08000064H  (Flash=FFH  Required=E3H) !
Contents mismatch at: 08000065H  (Flash=FFH  Required=02H) !
Contents mismatch at: 08000066H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000067H  (Flash=FFH  Required=08H) !
Contents mismatch at: 08000068H  (Flash=FFH  Required=E3H) !
Contents mismatch at: 08000069H  (Flash=FFH  Required=02H) !
Contents mismatch at: 0800006AH  (Flash=FFH  Required=00H) !
Contents mismatch at: 0800006BH  (Flash=FFH  Required=08H) !
Contents mismatch at: 0800006CH  (Flash=FFH  Required=E3H) !
Contents mismatch at: 0800006DH  (Flash=FFH  Required=02H) !
Contents mismatch at: 0800006EH  (Flash=FFH  Required=00H) !
Contents mismatch at: 0800006FH  (Flash=FFH  Required=08H) !
Contents mismatch at: 08000070H  (Flash=FFH  Required=49H) !
Contents mismatch at: 08000071H  (Flash=FFH  Required=0BH) !
Contents mismatch at: 08000072H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000073H  (Flash=FFH  Required=90H) !
Contents mismatch at: 08000074H  (Flash=FFH  Required=E3H) !
Contents mismatch at: 08000075H  (Flash=FFH  Required=02H) !
Contents mismatch at: 08000076H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000077H  (Flash=FFH  Required=08H) !
Contents mismatch at: 08000078H  (Flash=FFH  Required=E3H) !
Contents mismatch at: 08000079H  (Flash=FFH  Required=02H) !
Contents mismatch at: 0800007AH  (Flash=FFH  Required=00H) !
Contents mismatch at: 0800007BH  (Flash=FFH  Required=08H) !
Contents mismatch at: 0800007CH  (Flash=FFH  Required=E3H) !
Contents mismatch at: 0800007DH  (Flash=FFH  Required=02H) !
Contents mismatch at: 0800007EH  (Flash=FFH  Required=00H) !
Contents mismatch at: 0800007FH  (Flash=FFH  Required=08H) !
Contents mismatch at: 08000080H  (Flash=FFH  Required=E3H) !
Contents mismatch at: 08000081H  (Flash=FFH  Required=02H) !
Contents mismatch at: 08000082H  (Flash=FFH  Required=00H) !
Contents mismatch at: 08000083H  (Flash=FFH  Required=08H) !
Too many errors to display !
Error: Flash Download failed  -  "Cortex-M7"
Flash Load finished at 11:23:24

**Comment by whj4674672** [comment]
如果你无法提供**上面回答中需求的 3 张截图** 我无法解答你的问题。

**Comment by whj4674672** [comment]
用户自己工程配置错误导致，已解决
