### ISSUE TITLE
industry_io_gateway 工程在开启wifi时启动失败。

### ISSUE THREAD

**Issue by tjrong** [RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi#170]
这个wifi设备驱动结构体与wifi驱动库libwifi_6212_armcm7_2.1.2_gcc.a中的相差8个字节，是否驱动库与内核wlan不兼容。
这个结构体 libwifi_6212_armcm7_2.1.2_gcc.a库中的要少几个字节。
struct rt_wlan_device
{
    struct rt_device device;
    rt_wlan_mode_t mode;
    struct rt_mutex lock;
    struct rt_wlan_dev_event_desc handler_table[RT_WLAN_DEV_EVT_MAX][RT_WLAN_DEV_EVENT_NUM];
    rt_wlan_pormisc_callback_t pormisc_callback;
    rt_wlan_mgnt_filter_callback_t mgnt_filter_callback;
    const struct rt_wlan_dev_ops *ops;
    rt_uint32_t flags;
    struct netdev *netdev;
    void *prot;
    void *user_data;
};

**Comment by whj4674672** [comment]
@Guozhanxin

**Comment by tjrong** [comment]
现如何解决？

**Comment by whj4674672** [comment]
参考一下别人的实现 https://blog.csdn.net/lzs940320/article/details/111637309

**Comment by tjrong** [comment]
这个是看过的，内核WLAN是否一致？struct rt_wlan_device 这个结构体的大小？

**Comment by tjrong** [comment]
![image](https://user-images.githubusercontent.com/23478648/106408633-bbd43880-6479-11eb-919b-72fe73091c50.png)
上面的看过，就是一个配置;因为在初始化过程中就出现问题，主要是这个结构体不一致 struct rt_wlan_device，能否确认 下这个结构体在不同内核版本下的别？

**Comment by balanceTWK** [comment]
晚点我确认下！

**Comment by tjrong** [comment]
我想知道libwifi_6212_armcm7_2.1.2_gcc.a库是基于哪个内核版本的？
如下是我比较了4.02与4.03的区别。
struct rt_wlan_device
{
    struct rt_device device;
    rt_wlan_mode_t mode;
    struct rt_mutex lock;
    struct rt_wlan_dev_event_desc handler_table[RT_WLAN_DEV_EVT_MAX][RT_WLAN_DEV_EVENT_NUM];
    rt_wlan_pormisc_callback_t pormisc_callback;
//    rt_wlan_mgnt_filter_callback_t mgnt_filter_callback;  //4.03 比4.02多出来的字段 ，
    const struct rt_wlan_dev_ops *ops;
    rt_uint32_t flags;
    struct netdev *netdev;
    void *prot;
    void *user_data;
};

**Comment by tjrong** [comment]
屏蔽掉 // rt_wlan_mgnt_filter_callback_t mgnt_filter_callback; //4.03 比4.02多出来的字段 就正常了。
struct rt_wlan_device
{
struct rt_device device;
rt_wlan_mode_t mode;
struct rt_mutex lock;
struct rt_wlan_dev_event_desc handler_table[RT_WLAN_DEV_EVT_MAX][RT_WLAN_DEV_EVENT_NUM];
rt_wlan_pormisc_callback_t pormisc_callback;
// rt_wlan_mgnt_filter_callback_t mgnt_filter_callback; //4.03 比4.02多出来的字段 ，
const struct rt_wlan_dev_ops *ops;
rt_uint32_t flags;
struct netdev *netdev;
void *prot;
void *user_data;
};

**Comment by tjrong** [comment]
我一直在关注这个问题，有时间解决下？？

**Comment by balanceTWK** [comment]
struct rt_wlan_device
{
    struct rt_device device;
    rt_wlan_mode_t mode;
    struct rt_mutex lock;
    struct rt_wlan_dev_event_desc handler_table[RT_WLAN_DEV_EVT_MAX][RT_WLAN_DEV_EVENT_NUM];
    rt_wlan_pormisc_callback_t pormisc_callback;
    rt_wlan_mgnt_filter_callback_t mgnt_filter_callback;
    const struct rt_wlan_dev_ops *ops;
    rt_uint32_t flags;
    struct netdev *netdev;
    void *prot;
    void *user_data;
};

打库的工程用的是这个结构体。

**Comment by balanceTWK** [comment]
[libwifi_6212_armcm7_2.1.2_gcc.a.zip](https://github.com/RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi/files/5908345/libwifi_6212_armcm7_2.1.2_gcc.a.zip)

你看下这个好使不？好使的话，你帮我提交一个 PR 吧。

**Comment by tjrong** [comment]
[I/wn] RT-Thread webnet package (V2.0.2) initialize success.
[I/fs_op] sd card mount to '/sdcard'
[D/DBG] Set the block size

[D/DBG] Set the ALP

[D/DBG] Clear request for ALP

[D/DBG] Enable F2 interrupt only

[D/DBG] wwd_bus_sdio_download_firmware

[D/DBG] download firmware done!

[I/WWD] wifi initialize done. wiced version 3.3.1
[I/WLAN.dev] wlan init success
psr: 0x21030000
r00: 0xffffffff
r01: 0x00000014
r02: 0x00000000
r03: 0x7f210600
r04: 0xdeadbeef
r05: 0xdeadbeef
r06: 0xdeadbeef
r07: 0x240252d8
r08: 0xdeadbeef
r09: 0xdeadbeef
r10: 0xdeadbeef
r11: 0xdeadbeef
r12: 0x2401d961
 lr: 0x9002c7bf
 pc: 0x9002fe88
hard fault on thread: wifi_ini

thread   pri  status      sp     stack size max used left tick  error
-------- ---  ------- ---------- ----------  ------  ---------- ---
WWD        8  suspend 0x000000cc 0x00000800    30%   0x00000006 000
sdio_irq  15  suspend 0x000000b4 0x00000200    35%   0x00000014 000
webnet    20  suspend 0x0000019c 0x00001000    17%   0x00000004 000
ntp_sync  21  suspend 0x00000104 0x00000640    16%   0x00000064 000
mbt2r     19  suspend 0x000000fc 0x00000800    14%   0x00000064 000
ftp       27  suspend 0x0000010c 0x00000800    13%   0x00000064 000
sd_mount  29  suspend 0x000000b4 0x00000800    48%   0x00000060 000
wifi_ini  16  running 0x00000278 0x00001000    27%   0x0000000f 000
tshell    20  suspend 0x00000188 0x00001000    09%   0x00000009 000
acon      19  ready   0x00000128 0x00000800    14%   0x00000064 -02
telnet    26  suspend 0x00000178 0x00000800    18%   0x00000064 000
usbd       8  suspend 0x000000c8 0x00001000    04%   0x00000014 000
sys_work  23  suspend 0x00000084 0x00000800    06%   0x0000000a 000
mmcsd_de  22  suspend 0x000000b4 0x00000400    61%   0x00000004 000
wlan      15  suspend 0x00000084 0x00000800    13%   0x0000000a -01
tcpip     10  suspend 0x000000f0 0x00001000    14%   0x00000013 000
etx       12  suspend 0x000000ac 0x00000400    19%   0x00000010 000
erx       12  suspend 0x000000b8 0x00000400    62%   0x00000010 000
tidle0    31  ready   0x0000007c 0x00000200    35%   0x0000001f 000
timer      4  suspend 0x000000b0 0x00000200    35%   0x00000009 000
FPU active!
bus fault:
SCB_CFSR_BFSR:0x82 PRECISERR SCB->BFAR:7F210608

**Comment by tjrong** [comment]
还是要屏蔽掉 // rt_wlan_mgnt_filter_callback_t mgnt_filter_callback; 
我前调试到是相差8个字字，这里只是减少了4个字节，是否还有其它的字段？因为在驱动库中是动态分配出来的，在注册函数中进行清零并赋值；由于驱动中库中少了字段，动态分配出来会少字节；后来其它地方动态分配时就会覆盖掉(内核wlan框架中要使用的字段)

[I/FAL] RT-Thread Flash Abstraction Layer (V0.5.0) initialize success.
[Flash] (../packages/EasyFlash-v4.1.0/src/ef_env.c:1818) ENV start address is 0x00000000, size is 262144 bytes.
[Flash] EasyFlash V4.1.0 is initialize success.
[Flash] You can get the latest version on https://github.com/armink/EasyFlash .
[I/main] The operation path is "/norflash"
[I/fs_op] romfs mount to '/'
[I/FAL] The FAL MTD NOR device (filesystem) created successfully
[I/fs_op] norflash mount to '/norflash'
[I/OTA] RT-Thread OTA package(V0.2.3) initialize success.
[I/OTA] Verify 'wifi_image' partition(fw ver: 1.0, timestamp: 1592464902) success.
msh />[W/fs_op] sd card mount to '/sdcard' failed!
[I/wn] RT-Thread webnet package (V2.0.2) initialize success.
[I/fs_op] sd card mount to '/sdcard'
[D/DBG] Set the block size

[D/DBG] Set the ALP

[D/DBG] Clear request for ALP

[D/DBG] Enable F2 interrupt only

[D/DBG] wwd_bus_sdio_download_firmware

[D/DBG] download firmware done!

[I/WWD] wifi initialize done. wiced version 3.3.1
[I/WLAN.dev] wlan init success
[I/WLAN.lwip] eth device init ok name:w0
[W/ntp] Sync failed.
[W/WLAN.mgnt] F:rt_wlan_connect L:1092 not find ap! ssid:francist
[I/WLAN.mgnt] wifi connect success ssid:boyuan_R&D
[I/WLAN.lwip] Got IP address : 192.168.2.119

**Comment by tjrong** [comment]
![image](https://user-images.githubusercontent.com/23478648/106699817-92084680-661e-11eb-9ecf-7b4de16355fb.png)
![image](https://user-images.githubusercontent.com/23478648/106699917-bebc5e00-661e-11eb-98fa-213a3dcda246.png)
还是要屏蔽掉 // rt_wlan_mgnt_filter_callback_t mgnt_filter_callback; 这都是我屏蔽了一个指针的情况下;为

**Comment by balanceTWK** [comment]
你的 rt-thread 版本是 4.0.2 还是 4.0.3 ？

**Comment by tjrong** [comment]
4.03的，RTT的sdk上面的

**Comment by balanceTWK** [comment]
> 4.03的，RTT的sdk上面的，你有wifi驱动库是基于那个版本的？

也是 4.0.3

**Comment by tjrong** [comment]
![image](https://user-images.githubusercontent.com/23478648/106999618-7db07f00-67c1-11eb-9b10-abf678078da6.png)

![image](https://user-images.githubusercontent.com/23478648/106999685-9ae54d80-67c1-11eb-8ec3-ffbd4cfe6999.png)

**Comment by tjrong** [comment]
能否提供驱动源码？

**Comment by balanceTWK** [comment]
> 能否提供驱动源码？

你已经分析得这么深入了，我是非常想提供源码给你的，但是不行。同时我这边又没有时间深入去分析这个问题。

**Comment by tjrong** [comment]
你只是要简单调试可以看到了 bcm_hw_wlan_dev_alloc:你驱动的函数调用rt_malloc分配 ，rt_wlan_dev_register中会清零。看这两个函数的struct rt_wlan_device结构体大小就可以了。

**Comment by balanceTWK** [comment]
> 你只是要简单调试可以看到了 bcm_hw_wlan_dev_alloc:你驱动的函数调用rt_malloc分配 ，rt_wlan_dev_register中会清零。看这两个函数的struct rt_wlan_device结构体大小就可以了。

好！过两天解决！

**Comment by balanceTWK** [comment]
@tjrong  我有点怀疑是 rt_wlan_device 对齐的问题。

你那边的的优化等级是多少呀？我这边打一个和你优化等级一致的库试试看。

**Comment by tjrong** [comment]
优化等级是 -O0                       GUN 11

**Comment by balanceTWK** [comment]
我就是用的 O0 打的库。。。

![image](https://user-images.githubusercontent.com/30776697/107180510-ce1f1b00-6a13-11eb-8a77-0a798ad15934.png)

[libwifi_6212_armcm7_2.1.2_gcc.zip](https://github.com/RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi/files/5941492/libwifi_6212_armcm7_2.1.2_gcc.zip)

**Comment by balanceTWK** [comment]
如果还不行的话，你那边试试 这样：

![image](https://user-images.githubusercontent.com/30776697/107180647-19d1c480-6a14-11eb-85d5-f720c8e30cd8.png)

**Comment by tjrong** [comment]
为何看不到图片

**Comment by balanceTWK** [comment]
> 为何看不到图片

看这个截图：

您有一份文件待查收！即刻点击链接获取文件：https://cowtransfer.com/s/8d26b3b6dd4841 或进入 cowtransfer.com 获取，在首页输入取件码：293819（24小时内有效）

**Comment by tjrong** [comment]
bcm_hw_wlan_dev_alloc:
9007169c:   push    {r7, lr}
9007169e:   sub     sp, #8
900716a0:   add     r7, sp, #0
**900716a2:   mov.w   r0, #324        ; 0x144**


9002ce76:   b.n     0x9002cedc <rt_wlan_dev_register+184>
884           rt_memset(wlan, 0, sizeof(struct rt_wlan_device));
**9002ce78:   mov.w   r2, #332        ; 0x14c**
9002ce7c:   movs    r1, #0
9002ce7e:   ldr     r0, [r7, #12]
9002ce80:   bl      0x90004668 <rt_memset>

ALIGN(4)结果仍是一样

**Comment by balanceTWK** [comment]
ALIGN(8) 都试试

**Comment by tjrong** [comment]
\ | /
- RT -     Thread Operating System
 / | \     4.0.3 build Feb  8 2021
 2006 - 2020 Copyright by rt-thread team
lwIP-2.0.2 initialized!
[I/drv.rtc] RTC hasn't been configured, please use <date> command to config.
[E/drv.rtc] rtc register err code: -1
[I/SDIO] SD card capacity 15482880 KB.
found part[0], begin: 4194304, size: 14.780GB
[I/sal.skt] Socket Abstraction Layer initialize success.
struct rt_wlan_device len : 0x14c
device len : 0x54
flags len : 0x4
handler_table len : 0xb0
lock len : 0x28
mgnt_filter_callback len : 0x4
mode len : 0x1
netdev len : 0x4
ops len : 0x4
pormisc_callback len : 0x4
prot len : 0x4
user_data len : 0x4


msh >
 \ | /
- RT -     Thread Operating System
 / | \     4.0.3 build Feb  7 2021
 2006 - 2020 Copyright by rt-thread team
lwIP-2.0.2 initialized!
[I/sal.skt] Socket Abstraction Layer initialize success.
struct rt_wlan_device len : 0x144
device len : 0x50
flags len : 0x4
handler_table len : 0xb0
lock len : 0x24
mgnt_filter_callback len : 0x4
mode len : 0x1
netdev len : 0x4
ops len : 0x4
pormisc_callback len : 0x4
prot len : 0x4
user_data len : 0x4

我打印了两个工程输出长度，优化都是一样了，可能不是库的原因了

**Comment by tjrong** [comment]
#ifdef RT_USING_MODULE
    void      *module_id;                               /**< id of application module */
#endif
由于开启了MODULE,这个问题怎么处理？？

**Comment by tjrong** [comment]
帮我生成一个带动态库的WLAN库

**Comment by tjrong** [comment]
由于开启了MODULE，帮我生成一个支持MODULE的驱动，可以不？？

**Comment by Guozhanxin** [comment]
我们正在收集ART-Pi 相关使用问题 https://docs.qq.com/doc/DQlpvYVdCTGpRTFFm
我帮你记录上了。

**Comment by jackweics** [comment]
r11: 0xdeadbeef
r12: 0x00000000
 lr: 0x90036285
 pc: 0x9003620a
hard fault on thread: wifi_ini

thread   pri  status      sp     stack size max used left tick  error
-------- ---  ------- ---------- ----------  ------  ---------- ---
signal_l  16  suspend 0x000000ac 0x00000200    33%   0x00000064 000
signal_l  16  suspend 0x000000b0 0x00000200    34%   0x00000064 000
sd_mount  30  suspend 0x000000d0 0x00000800    13%   0x00000014 000
wifi_ini  16  running 0x00000204 0x00001000    21%   0x00000005 000
tshell    20  suspend 0x00000184 0x00001000    09%   0x0000000a 000
vcom      16  suspend 0x00000140 0x00000200    62%   0x00000014 000
usbd       8  suspend 0x000000c8 0x00001000    04%   0x00000014 000
sys_work  23  suspend 0x00000088 0x00000800    06%   0x0000000a 000
mmcsd_de  22  suspend 0x000000b4 0x00000400    54%   0x00000012 000
wlan      15  suspend 0x00000084 0x00000800    06%   0x0000000a 000
tcpip     10  suspend 0x000000ec 0x00000400    35%   0x00000014 000
etx       12  suspend 0x000000b0 0x00000400    17%   0x00000010 000
erx       12  suspend 0x000000b8 0x00000400    17%   0x00000010 000
ulog_asy  30  suspend 0x000000b0 0x00000400    32%   0x0000000d 000
tidle0    31  ready   0x00000074 0x00000100    51%   0x00000003 000
timer      4  suspend 0x00000080 0x00000200    25%   0x00000009 000
main      10  suspend 0x00000264 0x00000800    55%   0x00000014 000
bus fault:
SCB_CFSR_BFSR:0x82 PRECISERR SCB->BFAR:0C21CA7B
FATAL ERROR: Error reading from serial device

我也碰到这个问题，爬楼看了上面，注释了
struct rt_wlan_device
{
    struct rt_device device;
    rt_wlan_mode_t mode;
    struct rt_mutex lock;
    struct rt_wlan_dev_event_desc handler_table[RT_WLAN_DEV_EVT_MAX][RT_WLAN_DEV_EVENT_NUM];
    rt_wlan_pormisc_callback_t pormisc_callback;
    rt_wlan_mgnt_filter_callback_t mgnt_filter_callback;    ////4.03 比4.02多出来的字段 
    const struct rt_wlan_dev_ops *ops;
    rt_uint32_t flags;
    struct netdev *netdev;
    void *prot;
    void *user_data;
};
也不行
把里面的.a文件从这个帖子发的链接下载替换了也不行。
希望能尽快有个补丁。
