### ISSUE TITLE
浮点数设置错误

### ISSUE THREAD

**Issue by whj4674672** [RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi#177]
`STM32H7` 是 `cortex_m7` 的内核，他支持的是双精度浮点。

但是在 `RTT-Studio` 中设置的是 `fpv4-sp-d16` 这个是 `cortex_m4` 的单精度浮点数的设置。

所以应该修改为 `fpv5-d16`

这个应该修改哪个工程配置文件？

**Comment by mysterywolf** [comment]
这个？
![微信图片_20210313002032](https://user-images.githubusercontent.com/34888354/111076152-173c2080-8526-11eb-83b2-d995a6b46a30.png)
