### ISSUE TITLE
问题求教

### ISSUE THREAD

**Issue by andyMemory** [RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi#182]
请问industry_io_gateway例程中运行在web服务器中的网页是如何制作的？

**Comment by whj4674672** [comment]
@loogg

**Comment by loogg** [comment]
@WKJay 这位大佬帮忙做的，我对网页就了解一点

**Comment by WKJay** [comment]
@andyMemory 网页是使用 `html+javascript` 编写的
基于前端框架[vue3](https://v3.vuejs.org/guide/introduction.html)
UI库为[antd-vue 2.x](https://2x.antdv.com/components/overview/)
图表使用了[echarts](https://echarts.apache.org/en/index.html)
构建工具为[webpack](https://webpack.js.org/)
点击进入->[网页源码仓库](https://github.com/WKJay/ART-Pi-WEB/tree/ex)
希望能有所帮助

**Comment by andyMemory** [comment]
> @andyMemory 网页是使用 `html+javascript` 编写的
> 基于前端框架[vue3](https://v3.vuejs.org/guide/introduction.html)
> UI库为[antd-vue 2.x](https://2x.antdv.com/components/overview/)
> 图表使用了[echarts](https://echarts.apache.org/en/index.html)
> 构建工具为[webpack](https://webpack.js.org/)
> 点击进入->[网页源码仓库](https://github.com/WKJay/ART-Pi-WEB/tree/ex)
> 希望能有所帮助
