### ISSUE TITLE
program internal flash?

### ISSUE THREAD

**Issue by epikao** [RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi#239]
Hello,

Where can I find the program that is loaded in the internal flash of the STM32H750?

Thank you

**Comment by StackYuan** [comment]
Hi epikao:
Are you looking for internal bootloader?  You can find in /projects/art_pi_bootloader/
ART-PI's other project all based on External NorFlash, you may build and download bootloader first. If successfully booted, serial console can print out 'ART-PI BOOT' logo.
Thanks

**Comment by StackYuan** [comment]
> Hello,
> 
> Where can I find the program that is loaded in the internal flash of the STM32H750?
> 
> Thank you

Hi epikao:
Are you looking for internal bootloader? You can find in /projects/art_pi_bootloader/
ART-PI's other project all based on External NorFlash, you may build and download bootloader first. If successfully booted, serial console can print out 'ART-PI BOOT' logo.
Thanks

**Comment by epikao** [comment]
ok great thank you very much. Just another similar question:

See picture below, about art_pi_lvgl demo.
I still not understand the file-structure here. In the main.c the lv_demo.c file is never called.
So which file defines this?

![image](https://user-images.githubusercontent.com/26655950/197214232-bd39ef49-4204-4091-80bf-e484b070e319.png)

**Comment by epikao** [comment]
one more question:

I have the same ART-PI board, but the CS and CLK pin of the QSPI W25q64 is at a different position.

I thought now that I first open the bootloader project and adjust the pinout in the msp.c file (see screenshot), load the program on the chip (run) and then replace the STLDR file in the main program (Blink-LED) and then load the main program again (run).

Unfortunately this does not work, did I forget something? 

![image](https://user-images.githubusercontent.com/26655950/197477007-a5d2da53-e400-436b-94bb-0df23ae0bf19.png)

**Comment by epikao** [comment]
Yes, thank you very much
