### ISSUE TITLE
开机例程需完善问题记录

### ISSUE THREAD

**Issue by whj4674672** [RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi#43]
- [x] 修改蓝牙名称 ART PI 为 `ART-Pi`
- [x] 修改蓝牙固件读取方式
- [x] 提供网页源文件
- [x] 支持 ADB 
- [x] 获取到 IP 的情况，小程序再发送配网指令，不会返回 IP 地址
- [x] ymodem 传输失败
- [x] fal bench 速度比其他例程慢
- [x] 完善 README
- [x] FTP传输回导致终端卡死
- [x]  mac 地址不能都是 11:22:33:44:55:66
- [x] web 网页上的资源文件使用 CDN 缓存，提升页面装载速度
- [x] 更新 CDN 地址
- [x] 优化 html 代码

**Comment by WKJay** [comment]
> * [x]  修改蓝牙名称 ART PI 为 `ART-Pi`
> * [x]  修改蓝牙固件读取方式
> * [x]  提供网页源文件
> * [x]  支持 ADB
> * [x]  获取到 IP 的情况，小程序再发送配网指令，不会返回 IP 地址
> * [x]  ymodem 传输失败
> * [x]  fal bench 速度比其他例程慢
> * [ ]  完善 README
> * [x]  FTP传输回导致终端卡死

**Comment by WKJay** [comment]
网页加载有两种方案
- 完全从网络上获取静态资源
- 网络资源优先，本地资源备用

第一种方案可以大幅缩小需要上传的网页大小，甚至可以仅在程序中固化index.html从而无需上传文件。但是这种方案直接放弃了内网，即在内网环境下无法打开网页。并且在无法找到对应资源的情况下也会导致无法打开网页。

第二种方案在能够接入互联网的情况下可以很快打开页面，并在内网环境或者无法找到对应网络资源的情况下可以正常加载本地文件从而打开网页。但是其需要手动上传完整的网页文件。

**Comment by whj4674672** [comment]
已完成
