### ISSUE TITLE
art_pi_factory的adb初始化问题

### ISSUE THREAD

**Issue by Forest-Rain** [RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi#49]
在art_pi_factory工程中，adb软件包中adb_socket_init，是不是要调整到wifi_ready_handler()中，否则若wifi没有开自动重连或者wifi网络比较差连接慢，当前INIT_APP_EXPORT(adb_socket_init) 会先于wifi联网完成前执行，使得adb服务未正确启动，进而导致adb无法使用的情况.
ART-Pi错误提示:
"[7821] E/sal.skt: not find network interface device by protocol family(2).
[7829] E/sal.skt: SAL socket protocol family input failed, return error -3.
[7838] E/ADB iosk: Create socket error
"

**Comment by WKJay** [comment]
目前版本的 `adb_socket_init` 就是在 `wifi_ready_handler` 中的：
https://github.com/RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi/blob/master/projects/art_pi_factory/modules/wifi/wifi.c#L106

**Comment by Forest-Rain** [comment]
还有一个小问题就是WiFi异常断网后，ART-Pi若自动重连（启用），会出现bind失败，导致adb服务启动异常的情况
"[1507173] E/ADB iosk: adbd tcpip is exist
[1507180] E/ADB iosk: Unable to bind
"

**Comment by WKJay** [comment]
感谢反馈
