### ISSUE TITLE
RT-Thread Studio 1.1.4 ART-Pi使用情况反馈

### ISSUE THREAD

**Issue by Forest-Rain** [RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi#50]
1. RT-Thread Settings中，勾选某软件包下的某个子配置，该配置下的选项可能不会展开（该问题出现在有多个子配置的情况，且之前未配置过该项。目前的一种解决方式：重新取消选择软件包，再次勾选软件包，则可以看到）
2. “搜索”-》“C/C++搜索”-> "搜索字符串" 不支持 带空格的字符串（自动去除了空格）
3. 同时打开多个Studio会出现“无法锁定工作空间”错误提示
4. 同时存在多个ST-Link的时候，不支持ST-Link ID选择
5. “基于开发板”-> " STM32H750-RT-ART-Pi"-> "示例工程", 创建新工程，新工程中的board目录下缺少下载算法文件stldr/ART-Pi_W25Q64.stldr，也因此"配置工程" -> "Download" -> External Loader 未指定外部下载算法文件目录
6. art_pi_factory工程中有处笔误 RT-Thread Settings -> "库" -> "External Libraries " -> "Using **RT-Thrad** OTA Library"

**Comment by whj4674672** [comment]
RTT Studio 已经升级到v1.1.5以上问题都已修复
