### ISSUE TITLE
drv_gpio.c是否需要和rt-thread master同步

### ISSUE THREAD

**Issue by whj4674672** [RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi#83]
看到 rt-thread master 分支上的 drv_gpio.c 做了较大变动，我们这边需要同步更新嘛？会有什么问题？

@Guozhanxin

**Comment by Guozhanxin** [comment]
你可以看下，貌似是优化了速度，这个可以不同步吧，我们等正式release之后，整体更新下rtt版本就好了。

**Comment by whj4674672** [comment]
已经更新`PIN`框架
